name: flutter_jailbreak_detection
description: Flutter jailbreak and root detection plugin. This plugin wraps Rootbeer for use on Android and DTTJailbreakDetection for use on iOS. 
version: 1.10.0
homepage: https://github.com/jeroentrappers/flutter_jailbreak_detection

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: 3.19.2

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: appmire.be.flutterjailbreakdetection
        pluginClass: FlutterJailbreakDetectionPlugin
      ios:
        pluginClass: FlutterJailbreakDetectionPlugin
